version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/typespec/"
    schedule:
      interval: "weekly"
    groups:
      angular:
        applies-to: version-updates
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"