version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/typespec/"
    schedule:
      interval: "weekly"
    groups:
      typespec:
        applies-to: version-updates
        patterns:
        - "*"        # Matches all dependencies
        update-types:
        - "patch"    # Only allow patch updates for regular version updates
